name = "snappoints-customer-liff"
compatibility_date = "2026-02-18"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[env.preview]
name = "snappoints-customer-liff-preview"

[env.production]
name = "snappoints-customer-liff"
